version: '3.0'

services:
  db:
    image: postgres
    container_name: 'modal-db'
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5420:5432"