spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'user'
    password: 'user'
    url: 'jdbc:postgresql://localhost:5420/user'
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true